### ISSUE TITLE
Loading bam files is slow!

### ISSUE THREAD

**Issue by ahaque14** [chmille4/bam.iobio.io#33]
Hi All,

Good day and hope all is well.

We have recently installed bam.iobio.io locally with the help of the installation guide at this link: https://github.com/chmille4/iobio/wiki/Local-iobio-setup

However, when loading the bam files by selecting the 'choose bam file' button it takes very long to load and visualize the data. Our bam file is indexed according to http://bam.iobio.io/help.html. 

I am wondering if the bam file needs to be in the same virtual server for some reason where the webservice is running . Currently the bam files are in a separate node connected through a high speed data network.

Also is there any recommended server specification (cpu, memory etc.) for installing bam.iobio.locally?

Best Regards,

Anwar

**Comment by tonydisera** [comment]
Hi Anwar,

Loading local files will be slower, but not considerably slower. Is the file on you local file system or is it on a mounted drive on a remote file server? The latter will be slower. What kind of response times are you seeing? I am happy to investigate further if it is possible to send me the bam and bai files.

**Comment by ahaque14** [comment]
Hi Tony,

Thanks for your quick reply. The file is on our local file system in a Ubuntu VM. Regarding the response time it never finishes loading completely. The progress bar on the browser advances towards the end and then waits forever. We tried loading both local bam file and the bam file hosted in amazon aws by iobio site. In both the cases the progress bar stops with 'Initializing data' screen after a minute when it reaches towards the end. Please see attached screenshot.

Any idea or suggestion is appreciated to troubleshoot this problem.

Best Regards,
Anwar 

![initializing_data](https://cloud.githubusercontent.com/assets/12880188/8201573/fe50cbc8-14da-11e5-940f-76ddd3a7204b.jpg)
![initializing_data](https://cloud.githubusercontent.com/assets/12880188/8201579/0b8b37ec-14db-11e5-922a-11a20ee341b7.jpg)

**Comment by yiq** [comment]
Hi Anwar

It seems that you are having trouble connecting to the websocket backend services. This usually happens when your institution uses transparent proxy server, such as squid, to cache web contents. Here is a test you can run

https://www.websocket.org/echo.html

If you are only able to run the test with "TLS" checked, you are experiencing the well known condition, and we have a fix in the pipeline that will be rolled out pretty soon

**Comment by chmille4** [comment]
This could be a configuration issue. The current way of installing bam.iobio locally is fairly intricate. We have a docker container that we have been playing around with to simplify install down to a few commands.  Yi, do you have the docker install instructions?

**Comment by yiq** [comment]
Yea sorry I missed the part that this is a local bam.iobio installation. We
do have a docker image which wraps up all the parts that a local bam.iobio
needs. Try the script attached at the end of this email. It is of vital
importance that the environment variable "PUB_HOSTNAME" and "PUB_HTTP_PORT"
are passed in correctly, and that the directory mapped into the container
as /home/iobio/workdir, which mentioned in the script as /mnt/workdir, is
read-write-executable for the user 1000:1000

#!/bin/bash
#
# Example script to launch the bam.iobio docker image

# The following env vars will be honored by the container startup script

export PUB_HOSTNAME=$(hostname -f)
# alternatively, specify hostname manually if hostname -f does not
# return the approprate value
# export PUB_HOSTNAME="bam.iobio.io"
# or, if deploying on amazon cloud, retrieve public hostname via instance
meta-data
# export PUB_HOSTNAME=$(curl
http://169.254.169.254/latest/meta-data/public-hostname)

# The following ports need to be open for the public
export PUB_HTTP_PORT=8080

# pull the latest image
docker pull qiaoy/iobio-bundle.bam_iobio

# run the docker image interactively
# to daemonize the run, replace "-it --rm" with "-d"

# the line "-v $SWAP_DIR:/home/iobio/workdir" is optional, but would help
# performance between restarts. /mnt/workdir can be changed to any directory
# on the host filesystem that the user 1000/1000 has write access to. This
# directory will be used to store the index files, which are downloaded the
# first time the corresponding bam files are viewed.

SWAP_DIR=/mnt/workdir

swap_dir_find=`find -O0 $SWAP_DIR -uid 1000 -gid 1000 -type d 2>/dev/null`
if [ "x$swap_dir_find" != "x$SWAP_DIR" ]; then
    echo "$SWAP_DIR does not exist, or it has a ownership other than
1000:1000"
    echo "either create the directory and/or fix the ownership, or remove
the -v commandline parameter to docker"
    exit 1
fi

# Launch the container

docker run -it --rm \
    -p $PUB_HTTP_PORT:80 \
    -v $SWAP_DIR:/home/iobio/workdir \
    -e PUB_HOSTNAME \
    -e PUB_HTTP_PORT \
    qiaoy/iobio-bundle.bam_iobio

**Comment by ahaque14** [comment]
Hi Yi,

Thanks for providing us the docker install instructions which we tried to install without success. So we went back to the original instructions at this link: https://github.com/chmille4/iobio/wiki/Local-iobio-setup

As we followed the original instructions we are getting the following two errors for one of the web services which might be the cause why the bam file never finishes loading:

(1) http requestundefined
samtools ERROR: [knet_seek] SEEK_END is not supported for HTTP. Offset is unchanged.

(2) Error: Cannot find module 'follow-redirects'
    at Function.Module._resolveFilename (module.js:338:15)
    ........ 

Details log are pasted below:
(1) 
parUrl = ws://172.32.67.156:8060?cmd=view%20-H%20http://172.32.67.156/bam.iobio.io/lun/accepted_hits.bam
parts1 = cmd=view%20-H%20http://172.32.67.156/bam.iobio.io/lun/accepted_hits.bam
urlParams = cmd=view%20-H%20http://172.32.67.156/bam.iobio.io/lun/accepted_hits.bam
parameterPair = cmd=view%20-H%20http://172.32.67.156/bam.iobio.io/lun/accepted_hits.bam
cmad = ws://172.32.67.156:8060?cmd=view%20-H%20http://172.32.67.156/bam.iobio.io/lun/accepted_hits.bam
raw args = view,-H,http://172.32.67.156/bam.iobio.io/lun/accepted_hits.bam
command: /home/iobio/iobio/bin/samtools view,-H,http://172.32.67.156/bam.iobio.io/lun/accepted_hits.bam,-
http requestundefined
samtools ERROR: [knet_seek] SEEK_END is not supported for HTTP. Offset is unchanged.

parUrl = ws://172.32.67.156:8888?cmd=-i%20http://172.32.67.156/bam.iobio.io/lun/accepted_hits.bam.bai
parts1 = cmd=-i%20http://172.32.67.156/bam.iobio.io/lun/accepted_hits.bam.bai
urlParams = cmd=-i%20http://172.32.67.156/bam.iobio.io/lun/accepted_hits.bam.bai
parameterPair = cmd=-i%20http://172.32.67.156/bam.iobio.io/lun/accepted_hits.bam.bai
cmad = ws://172.32.67.156:8888?cmd=-i%20http://172.32.67.156/bam.iobio.io/lun/accepted_hits.bam.bai
raw args = -i,http://172.32.67.156/bam.iobio.io/lun/accepted_hits.bam.bai
command: /home/iobio/iobio/bin/bamReadDeptherHelper.sh -i,http://172.32.67.156/bam.iobio.io/lun/accepted_hits.bam.bai
http requestundefined



(2) 
module.js:340
    throw err;
          ^
Error: Cannot find module 'follow-redirects'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Function.module.exports.httpRequest (/home/iobio/iobio/minion.js:226:11)
    at Function.module.exports.runCommand (/home/iobio/iobio/minion.js:199:22)
    at BinaryClient.<anonymous> (/home/iobio/iobio/minion.js:83:28)
    at BinaryClient.EventEmitter.emit (events.js:98:17)
    at /home/iobio/iobio/node_modules/binaryjs/lib/client.js:117:16
    at process._tickCallback (node.js:415:13)
error: Forever detected script exited with code: 8
error: Script restart attempt #1
iobio server started on port 7777


Any suggestion is highly appreciated.

Best Regards,
Anwar

**Comment by yiq** [comment]
Hi Anwar

  Sorry to hear that the docker image didn't work out for you. We are in
the process of dockerizing all our services and apps, and have seen
successful adoption at many places. The original instruction you have been
referring to is obsolete, and contains stale information. If you want, I'd
be glad to help you get docker-based local installation up and running. If
you could send me the script you tried to run the docker image, the console
prompt, and potentially the content of the folder /var/log inside the
container (with "$ docker cp <container_name>:/var/log ./", it would be
very helpful for me to figure out what went wrong

As for the error you saw in the log file. The first is fine, but I think
the second is what causing the problem. We have updated iobio so that it
can handle URL-redirect, but the change was never reflected in the install
instruction. Thus, a nodejs module is missing. Please run, inside the iobio
directory,  "npm install". It will install all required dependencies.
Again, the instruction is not very up to date because we are transitioning
to docker, which should hide all these technical details from users.

Let me know if it works

Best wishes
Yi

**Comment by ahaque14** [comment]
Hi Yi,

We were able to run the iobio web application from the docker image you provided. However, it did not resolve the previous issue of the progress bar stopping with 'Initializing data' screen after a minute when it reaches towards the end and never loads completely.

Is there a detailed step by step clean installation instruction that you can provide which worked in your Ubuntu?

I am unable to attach the log file here. I can send you the log file if you provide me an email address.

Thanks,
Anwar

**Comment by yiq** [comment]
its weird. yea definitely send the log to atrusqiao (at) gmail (dot) com. I'll give it a look. The same script I attached here earlier is used to run bam.iobio on our own infrastructure without any hiccup.

**Comment by ahaque14** [comment]
Below is the error we are getting while trying to load the bam file from a http location. I emailed you the entire log folder also.


2015/07/08 07:47:11 [error] 23#0: *18 connect() failed (111: Connection refused) while connecting to upstream, client: 172.32.67.156, server: _, request: "GET /bamstatsalive/ HTTP/1.1", upstream: "http://[::1]:8004/", host: "iobio-dev:8080"
2015/07/08 07:47:12 [error] 23#0: *21 connect() failed (111: Connection refused) while connecting to upstream, client: 172.32.67.156, server: _, request: "GET /samtools/?id= HTTP/1.1", upstream: "http://[::1]:8001/?id=", host: "iobio-dev:8080"

**Comment by yiq** [comment]
@ahaque14 

I updated the docker image in a few ways. You guys might want to give it a try to see if it improve things. So you are actually trying to get it run inside a virtual machine right? It might complicate a few things, most significantly is that your virtual machine probably don't have a full qualified domain name. Bam.iobio is a combination of client and server side technology so that the web site, which runs inside the web browser, needs to be able to make connection to the services inside the docker container; but at the same time, services inside the container needs to be able to reach each other at the same time, with the same hostname. You can assign a hostname (e.g. "ubuntu") to your virtual machine, and have an entry in /etc/hosts (e.g. 127.0.0.1  ubuntu). But inside the docker container the name "ubuntu" probably won't resolve.

A work-around for virtual machine is to make sure the following:
  - make sure the PUB_HOSTNAME to be localhost
  - make sure the PUB_HTTP_PORT is 80

This would ensure that, whether inside the container or not, services are always accessed through http://localhost:80/

Please give the following script a try:
```
#!/bin/bash
#
# Example script to launch the container

# The following env vars will be honored by the container startup script

#export PUB_HOSTNAME=$(hostname -f)
export PUB_HOSTNAME=localhost
export PUB_HTTP_PORT=80

# Launch the container

docker run -it \
        -p $PUB_HTTP_PORT:80 \
        -e PUB_HOSTNAME \
        -e PUB_HTTP_PORT \
        --name bam_iobio \
        --rm qiaoy/iobio-bundle.bam_iobio
```

after it starts, point your browser at http://localhost/, and make sure that the example URL works (click on "choose bam url", and then hit "go"). If it works, it means that the services are running properly and can orchestrate with each other. Otherwise, send me the log ;)

What's your ultimate use-case? do you have bam files sitting in a NFS folder you want to visualize, or are they accessible over HTTP from some server? I'll need to make another for the former case; for the latter, it should work just fine. The only thing to make sure is that the http server can be accessed from within the docker container (e.g. a nginx running inside the virtual machine probably is a bad idea).

let me know how it goes

**Comment by abdoukadri** [comment]
Thanks All for your help for having this working, 

We are trying to access files over HTTP from a server. This server and our bam iobio docker server both resides on the same cluster and BOTH servers need VPN connections.

Using our locally installed server(i.e. using docker), we are able to visualise any public data(including the amazon files) and loaded from choosing a local bam file and its index. BOTH works fine.

But only problem is trying to visualise our own locally hosted file through http. for example
http://localBamiobio:80/?bam=http://bamfilesever:8080/bam/file1.bam

The Bam iobio page loads but no data get visualised (Initializing data... will go for ever)

We tried all pervious directions and settings but with no luck

I would appreciate any suggestion to get this working.

**Comment by yiq** [comment]
Not even the coverage plot? This means that the iobio backend services running inside the docker container cannot access the bam and bai files. I draw a little illustration on all the network communications that needs to happen for bam.iobio to work

![bamiobio](https://cloud.githubusercontent.com/assets/362496/10053310/9968334e-61e8-11e5-906a-eadfb35f8792.png)

make sure that all mentioned requests can be accomplished with respect to inside / outside docker. E.g. step 5 and 6 are initiated from within the docker container. So bamfileserver needs to be resolvable there.
