### ISSUE TITLE
User definable x and y axis values

### ISSUE THREAD

**Issue by AlistairNWard** [chmille4/bam.iobio.io#51]
There is a usecase for this with, for example, trios. I have three samples and I want to compare them to each other (and ultimately include read coverage distribution in a final report). For comparison across samples, I want to ensure that the x- and y- axes limits are set to be the same, e.g. as I tab across the three bam.iobio instances, it is easy to see a discrepancy in one file.

**Comment by tonydisera** [comment]
Hi Al.  I noticed that this issue is in the 'Ready' column.  I've assigned the other issues to Megan, but I didn't know if this is one we wanted tackled right now.  If so, can you please assign it to Megan?
Thanks!
Tony

**Comment by AlistairNWard** [comment]
I think this is something that would be beneficial in the short term, so I'd like it on the docket if possible. I've assigned it to Megan.

**Comment by mjbowler** [comment]
Al, I have this working.  Do you have a preference for UI?  
This is what I have in a popup window currently, but I can rename everything as we see fit.  I can also send in the actual axes names like "define lower limit for frequency" instead of just saying 'y axis'.  
Also, I have reset clearing everything and reverting to default ranges.  Would you want the ability to reset back to what is currently on the screen?  Like 'reset' would put back the values on the screen and there'd be a third option called 'restore to default' or something like that.  
Finally, I have this accessible by double clicking the either of the axis labels, is this okay?
![DefineAxes.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a68fe5f7453d30014ef4f07/125516c66e82c728ace21e0d46cc919c2a8c868897ecac01e81fe086264c22703d46f96925dde071be1123050a584baa405c5f44fbac8e28afb73f79984019af80330b2b9b645bf9fa9015ad00b22a8a4a84beb88d4fc8ea3b20ee829d02.png)

**Comment by AlistairNWard** [comment]
I think this works; at least to get in a staging version of bam for people to test and comment on. 

1. I agree that it would be better to pull in axis names, so that it is clear what values you are setting.

2. I think the reset would just return to what bam.iobio had set it's own axis values to. Probably no need for a third option, but again, if we get the basic functionality available, maybe others will have a use case that I haven't considered.

3. We probably need something a little more obvious to the user for modifying this, but as an initial solution for testing, I think this is fine. We could look at having a settings button for the chart that would provide this functionality, and then collect all available actions together (the only other action currently is to pull up info). This may be no clearer though!!

![screen shot 2018-02-12 at 9 40 55 pm](https://user-images.githubusercontent.com/523111/36131077-0d356db8-103e-11e8-9cfd-5a22a63304f4.png)
