### ISSUE TITLE
Hangs with no index file

### ISSUE THREAD

**Issue by AlistairNWard** [chmille4/bam.iobio.io#75]
Launching bam.iobio from GNomEx when no index exists causes bam to hang. Error in console is:

bam read depther Error: Vkl391RY2Q: prog process exited with code 1

We should have an error message provided to the user.

**Comment by mjbowler** [comment]
Do we have an example of one such file?  Or should I look for any that doesn't have an accompanying .bai file? Thanks!

**Comment by AlistairNWard** [comment]
I just created one:

https://s3.amazonaws.com/iobio/samples/test_files/141-16_S2.bam

**Comment by mjbowler** [comment]
We no longer get that error - at least not on the Vue version of bam.  Instead we just have no data returned from the bam iobio javascript object which causes an error later.  Is there any helper function in samtools that can check for the validity of a bai url or something like that?  (I can check for the error later but it's not guaranteed to be caused by a lack of index file, so I hate to have that be an error message.)

**Comment by chmille4** [comment]
I don't think samtools has that ability.  However, when you catch the error you could do a simple ajax call to check if the ```.bai``` file exists and if not then you can give a more descriptive answer.

Something like this code snippet below should do a simple check. Since you are doing ```type:HEAD```, you simply get the http header and don't download the bai file, which could be slow.

```
function urlExists(url, callback){
  $.ajax({
    type: 'HEAD',
    url: url,
    success: function(){
      callback(true);
    },
    error: function() {
      callback(false);
    }
  });
}
```

**Comment by mjbowler** [comment]
Sounds good.  I was going to do something similar, but thought I'd ask about samtools just in case.

**Comment by mjbowler** [comment]
Checking the URL doesn't work.  I get the same result regardless of if the index file is there or not.  There are also problems with Access Control depending on the file's supposed location.  I've put a check in where we hit the error instead and issue an alert.
